import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { BackgroundBeams } from "@/components/ui/background-beams"; // Import BackgroundBeams
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative min-h-screen w-full bg-neutral-950`}
      >
        {/* BackgroundBeams component for all pages */}
        <div className="absolute inset-0 z-0">
          <BackgroundBeams />
        </div>

        {/* Page Content */}
        <div className="relative z-50">{children}</div>
      </body>
    </html>
  );
}
